import type { Metadata } from 'next'
import { Exo_2 } from 'next/font/google'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css'
import './globals.css'

const exo_2 = Exo_2({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Wheely',
  description: 'Generated by create next app'
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html data-bs-theme="dark" lang="ru">
      <Head>
        <title>Wheely</title>
        <meta name='viewport' content='width=device-width, initial-scale=1'/>
      </Head>
      <body className={exo_2.className}>
        {children}
      </body>
    </html>
  )
}
